import type { Metadata } from "next";
import "../../ui/styles/globals.css";
import { NavBar } from "@/ui/components/nav-bar/NavBar";
import { SideBar } from "@/ui/components/side-bar/SideBar";

export const metadata: Metadata = {
  title: "EdYOf Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased bg-gray-200">
        <NavBar/>
        <main className="flex w-full py-4 pr-4">
          <SideBar />
          {children}
        </main>
      </body>
    </html>
  );
}
